services:
  - type: web
    name: oeng-app-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        fromDatabase:
          name: oeng-app-secrets
          property: FIREBASE_PROJECT_ID
      - key: FIREBASE_PRIVATE_KEY
        fromDatabase:
          name: oeng-app-secrets
          property: FIREBASE_PRIVATE_KEY
      - key: FIREBASE_CLIENT_EMAIL
        fromDatabase:
          name: oeng-app-secrets
          property: FIREBASE_CLIENT_EMAIL
      - key: GOOGLE_GENERATIVE_AI_API_KEY
        fromDatabase:
          name: oeng-app-secrets
          property: GOOGLE_GENERATIVE_AI_API_KEY
      - key: STRIPE_SECRET_KEY
        fromDatabase:
          name: oeng-app-secrets
          property: STRIPE_SECRET_KEY
      - key: STRIPE_WEBHOOK_SECRET
        fromDatabase:
          name: oeng-app-secrets
          property: STRIPE_WEBHOOK_SECRET
    autoDeploy: true
    branch: main
    rootDir: .
    
databases:
  - name: oeng-app-secrets
    databaseName: oeng-app-secrets
    user: admin